### ISSUE TITLE
Behavior when output file is deleted while LS is running

### ISSUE THREAD

**Issue by suyograo** [logstash-plugins/logstash-output-file#20] opened 2015-11-16 18:21 UTC
From a user:
----------------------------------------------------------------------
if I delete an output file that Logstash has been writing to while it is running it does not recreate that file, and it does not error. It just acts like everything is fine and drops all the messages.

This is a bit concerning.

Is there anyway to change this default behavior to create the file if it is missing? Or at least throw an to error?

Steps to reproduce: 
- start up logstash with file output 
- send in input so it creates an output file 
- delete that output file 
- send some more data in 
- logstash will not complain, but no data will be written

Restarting logstash makes it find those files again.

**Comment by jordansissel** [comment] 2015-11-16 19:01
This is normal behavior of POSIX/Unix systems. For some backstory, when you delete a file, you're doing what's called "Unlinking" - that unlinking removes the reference mapping the name to the inode on disk.

The data is still written to that same file even after you delete it (or rename it). It isn't lost, in a way, only the reference (name) to the data is lost when you remove the file by name. I may be doing a poor job of explaining this behavior, sorry if so!

Anyway, I think I understand the behavior you're wanting, and maybe we can provide it somehow with a new setting, maybe.

**Comment by purbon** [comment] 2015-11-16 19:03
@jordansissel thanks for the comment, will be working on that and trying to explore best solution for this.

**Comment by purbon** [comment] 2015-11-17 07:47
Fixed in https://github.com/logstash-plugins/logstash-output-file/pull/21, @jordansissel @suyograo feel free to provide your feedback.

**Comment by turtlemonvh** [comment] 2015-11-17 19:19
I am the user who originally sent this in as a support request, and I can confirm that #21 does handle recreation of the files successfully under our usage patterns.

Thanks!

**Closed** 2015-11-19 08:32 UTC
Labels: bug

**Comment by purbon** [comment] 2015-11-19 09:03
published a new version of the plugin that include this changes https://rubygems.org/gems/logstash-output-file/versions/2.1.0 if you want to grab them, need to run ```bin/plugin update logstash-output-file``` or ```bin/plugin install --version 2.1.0 logstash-output-file``` (if you want to install).

**Comment by turtlemonvh** [comment] 2015-11-19 17:18
Thanks @purbon!

**Comment by turtlemonvh** [comment] 2015-11-20 14:06
The specific steps I had to take to install (because of the issues with concurrent ruby mentioned in [this ticket](https://github.com/elastic/logstash/issues/4141)) were

    # Running as root
    if ! grep -q "concurrent-ruby" /opt/logstash/Gemfile ; then
        echo 'gem "concurrent-ruby", "0.9.1"' >/opt/logstash/Gemfile
    fi
    /opt/logstash/bin/plugin update logstash-output-file
    /opt/logstash/bin/plugin install --version 2.1.0 --no-verify logstash-output-file
