### ISSUE TITLE
Plugin is closing file with periodic updates

### ISSUE THREAD

**Issue by ceeeekay** [logstash-plugins/logstash-output-file#59] opened 2018-01-24 22:40 UTC
I have heartbeat input generating messages which I'm sending to a file for Icinga to monitor. 

Since upgrading Logstash from 5.6.5 to 6.1.2 I'm seeing a lot of open/close messages for this file in the Logstash logs. 

Has the timeout on open files changed, and is there any way to override this?

- Version: 4.2.1
- Logstash Version: 6.1.2
- Operating System: Ubuntu 16.04.3
- Config File:
```
input {
  heartbeat {
    message => "epoch"
    interval => 15
    type => "heartbeat"
  }
}
[...]
output {
  if [type] == "heartbeat" {
    file {
      path => "/tmp/heartbeat"
      codec => line {
      format =>  [ "%{clock} " ]
    }
  }
}
```
- Sample Data: 
`/var/log/logstash/logstash-plain.log`
```
[2018-01-25T11:23:49,152][INFO ][logstash.outputs.file    ] Closing file /tmp/heartbeat
[2018-01-25T11:23:53,261][INFO ][logstash.outputs.file    ] Opening file {:path=>"/tmp/heartbeat"}
[2018-01-25T11:24:19,198][INFO ][logstash.outputs.file    ] Closing file /tmp/heartbeat
[2018-01-25T11:24:23,271][INFO ][logstash.outputs.file    ] Opening file {:path=>"/tmp/heartbeat"}
[2018-01-25T11:24:49,568][INFO ][logstash.outputs.file    ] Closing file /tmp/heartbeat
[2018-01-25T11:24:53,260][INFO ][logstash.outputs.file    ] Opening file {:path=>"/tmp/heartbeat"}
[2018-01-25T11:25:19,877][INFO ][logstash.outputs.file    ] Closing file /tmp/heartbeat
```

**Comment by Programie** [comment] 2018-09-06 11:27
I have the same issue with hundreds of files being written to using the logstash-output-file plugin and having a lot of Opening file and Closing file messages in the log.

I guess, opening and closing the same files all the time also increases the CPU/system load as it is in my case. I'm currently not sure whether it's caused by the massive opening/closing of files, but it looks like to be related to it as it only happens on the logstash host that is writing to files.

**Comment by ceeeekay** [comment] 2018-09-06 11:36
I wouldn't hold your breath for any sort of response from the devs.. They seem to want to ignore this issue for some reason.

**Comment by BulatSaif** [comment] 2019-02-21 11:12
I started using logstash  6.3.2  same problem :(

**Comment by imweijh** [comment] 2019-10-16 09:47
logstash 7.4.0 same problem ...

**Closed** 2020-04-27 10:19 UTC
